### ISSUE TITLE
volumetric beam vs. background

### ISSUE THREAD

**Issue by dafhi** [erichlof/THREE.js-PathTracing-Renderer#57]
just checked out the volumetric demo, and if you strafe downward you can see the beam nice and bright against the box but vanishes over background infinity

**Comment by erichlof** [comment]
@dafhi 
Hi David!

Thank you for bringing this to my attention.  I wouldn't have spotted it for a long time because I don't usually fly below the Cornell box, lol!  It turned out to be a relatively simple fix.  Should be working properly now: [Volumetric Demo](https://erichlof.github.io/THREE.js-PathTracing-Renderer/Volumetric_Rendering.html)

Thanks again!
-Erich

**Comment by dafhi** [comment]
there is still a problem.  where the glass sphere shadow hits the wall it is darker than background inf, but the beam is lighter

**Comment by erichlof** [comment]
@dafhi 
Could you please post a screenshot with the artifact up fairly close to the camera, and  near the center of the screen?  I'm not seeing anything yet on my end.  Thanks

Edit: Nevermind, I found what you were referring to.  Hopefully it's fixed now.  There are still minor discrepancies when you fly right beneath the glass sphere and right through it's shadow that is cast below it, all while focusing on the beam.  The beam seems to darken just a little bit.  But I don't have much control over this phenomenon because it relates to the original volumetric equidistant sampling function I used from the fairly recent CG research paper from the company Solid Angle, creators of the professional Arnold Renderer package (the comments above the equidistant volume sampling function in my shader code gives credit and points to the source where I obtained this unique and efficient routine).  To get rid of every last small light-physics artifact, I would need as deep of an understanding as they did when they created this novel function.  Alas, this is not the case, lol.

**Comment by erichlof** [comment]
Looks pretty smooth to my eyes now :)

![VolumetricCaustic](https://user-images.githubusercontent.com/3434843/116617252-3e4a8800-a903-11eb-8a11-c9dd973b0f53.png)

**Comment by dafhi** [comment]
yes, great.   i dont know how to take a screenie w my new laptop lol.  also im a tad bit sketchy in my reasoning sometimes, overlooking specifically that this is scattering and not luminal, like a laser medium.  still, it was noticeable.

i've only just today seen the dynamic sample radius update.  really cool.

**Comment by erichlof** [comment]
@dafhi 
Yeah I had to Google how to take a screenshot, lol!  Basically, once you have your computer screen showing what you want other people  to see (be careful,  no personal online bank websites in the background,  ha),  there's a key near the top right of most keyboards, to the right of F12, called Prtsc, which stands for print screen. You just tap that button once, and unfortunately there's no feedback, but be assured that it silently saved it to your clipboard, ha. 

Now to see it and possibly edit it (or not), you have to open up a simple image program  - I use Paint on my Windows device. Once you're in Paint or other image manipulation program, find the Paste button at top left and click that and your clipboard image should pop into view inside the Paint program. Then just hit File, Save as.. I normally choose .png (good quality vs. compression for web), then name it something and you're good to go!  To post an image here on the issues/pr message boards for example, just drag the saved image's icon right inside this field where you are typing your replies, Github does the rest!

Again, thanks for bringing the volumetric rendering artifacts to my attention. Glad you liked the radius sample update - it helps a lot! :-)

Cheers,
-Erich

**Comment by dafhi** [comment]
old laptop had ptrsc .. new laptop is Asus g15 .. they make a few keyspace compromises

**Comment by erichlof** [comment]
How do they expect you to be able to take a screenshot then? lol 
It's funny, I never knew what prtscr did on all computers I ever owned prior to my current humble laptop where, all of a sudden I needed to send a screenshot.  On the prtscr key, it has the word sysrq (what is that?) right under it. It was one of those mysterious buttons that I dared not touch, ha ha!

**Comment by dafhi** [comment]
on win10 i found out you can [winkey] + shift + s.  my old lapper also has prtsc / sysreq.  looks like linux makes use of it.  odd system calls i guess
